### ISSUE TITLE
Links to doi2bib.org are broken

### ISSUE THREAD

**Issue by santisoler** [compgeolab/website#21]
The "BibTeX" button of each publication points to `doi2bib.org` to actually get a BibTeX citation.
Nevertheless, the links don't work properly. Apparently `doi2bib.org` does something else when clicking on the "get BibTeX" button, so it's not possible to get the citation by just going into an url like https://www.doi2bib.org/bib/10.1093/gji/ggab297

**Comment by leouieda** [comment]
I noticed this today. It seems that there is some local caching being done by doi2bib because that link works on my laptop but not my phone or tablet. 

I think I'll store citation and bibtex in the yaml file and make the buttons open a collapsed div like the abstract. That's probably a more robust thing to do .

**Comment by leouieda** [comment]
Fixed. Should be good now.
